<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_CB3d73d0f8</name>
   <tag></tag>
   <elementGuidId>76ce33ae-3b77-41d3-aa7b-7cc58daee832</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.mat-cell.cdk-cell.clickableLinkGeneric.cdk-column-name.mat-column-name.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div[2]/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7338d7df-4a98-4c58-ba69-692bc5d307f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>e78fbe64-11e6-40b7-8013-5c76628ce74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell clickableLinkGeneric cdk-column-name mat-column-name ng-star-inserted</value>
      <webElementGuid>b9ed7634-8a77-4d3a-a4a6-0197f97cd206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> CB3d73d0f8 </value>
      <webElementGuid>dc3938fa-d45a-46a6-8546-5401e695b062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c202-6 ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;mat-elevation-z8 paymentSizing ng-star-inserted&quot;]/table[@class=&quot;mat-table cdk-table mat-sort&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell clickableLinkGeneric cdk-column-name mat-column-name ng-star-inserted&quot;]</value>
      <webElementGuid>62e2f393-069d-4828-8ae4-c9adc7a1c577</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div[2]/table/tbody/tr/td</value>
      <webElementGuid>7c2b829d-221b-46e9-9065-52e670b453c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Method'])[1]/following::td[1]</value>
      <webElementGuid>c21a07d8-583f-483f-be52-a6b845327b6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date'])[1]/following::td[1]</value>
      <webElementGuid>de18e202-a778-487a-90ca-0f4f708817c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1.56'])[1]/preceding::td[1]</value>
      <webElementGuid>fd500887-b272-4d03-951e-9854132a725c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VISA 100'])[1]/preceding::td[3]</value>
      <webElementGuid>8a63a9b4-e59c-4e9f-a96e-9a356aee3f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CB3d73d0f8']/parent::*</value>
      <webElementGuid>da6fafc4-0197-4740-a78b-5adc80b55b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>9e9dac24-9034-48c0-9ecd-ffc72e389c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' CB3d73d0f8 ' or . = ' CB3d73d0f8 ')]</value>
      <webElementGuid>a9ea07ab-1b26-4c01-8410-416df63b1f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
