<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_INV-002647</name>
   <tag></tag>
   <elementGuidId>17de578a-ebc3-4150-95ef-b7ebcd826a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.mat-cell.cdk-cell.clickableLinkGeneric.cdk-column-invoiceNumber.mat-column-invoiceNumber.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date'])[1]/following::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5bc79bc0-e7cd-4e33-8c9a-eb856254ea48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>7a15c3b9-b42c-4f38-8998-ef45f0e5d391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-cell cdk-cell clickableLinkGeneric cdk-column-invoiceNumber mat-column-invoiceNumber ng-star-inserted</value>
      <webElementGuid>a2ad4afa-792f-47f8-95d6-0d2bf5fff6d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> INV-002647 </value>
      <webElementGuid>d5697978-391e-4b07-8ad4-fc19847f3e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-invoice-list[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 openInvoicesSizing&quot;]/table[@class=&quot;mat-table cdk-table mat-sort ng-star-inserted&quot;]/tbody[1]/tr[@class=&quot;mat-row cdk-row ng-star-inserted&quot;]/td[@class=&quot;mat-cell cdk-cell clickableLinkGeneric cdk-column-invoiceNumber mat-column-invoiceNumber ng-star-inserted&quot;]</value>
      <webElementGuid>4ed86edc-6574-4e61-9ab4-309d5318aee8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date'])[1]/following::td[1]</value>
      <webElementGuid>bb2f4689-3984-4f14-9794-00cd880018cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::td[1]</value>
      <webElementGuid>5f84f54b-7a4b-43f7-b44f-6b2edaabf572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$249,956.13'])[1]/preceding::td[1]</value>
      <webElementGuid>739bf787-1ab4-4dfa-ac6f-6d171d92b2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250,000.00'])[1]/preceding::td[2]</value>
      <webElementGuid>c52e294b-30e6-4d8f-bbe5-e7282f97fbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INV-002647']/parent::*</value>
      <webElementGuid>ca5cd0e0-40c3-4569-b117-cb9ea0862b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>67f857f7-5535-40dc-912b-898b3444b529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' INV-002647 ' or . = ' INV-002647 ')]</value>
      <webElementGuid>53d8abfb-5938-4f8a-8d3a-fd075d34f4f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
