<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Billing Address_mat-input-3</name>
   <tag></tag>
   <elementGuidId>3bdfe486-8d4d-45c1-a74e-a4a5a7d3cd2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mat-input-3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-input-3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>27276c8d-1abe-46dd-aeff-d53ba38405dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>83711908-f564-4dfd-ac80-0e371240dfb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c73-3 ng-untouched ng-pristine ng-invalid cdk-text-field-autofill-monitored</value>
      <webElementGuid>b063f8dd-c122-4fd0-9e41-e1455c92f7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-3</value>
      <webElementGuid>4c854099-810b-45a0-b925-7e7ead6c8dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Email Address</value>
      <webElementGuid>1e7f872a-5bef-4942-a937-1ac7431bc882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>68a4b718-55ee-4203-9db1-24982e3832bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc33248e-266d-4429-b391-62c3f27e7c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-3&quot;)</value>
      <webElementGuid>9005778b-c877-4a01-b1b8-61daa96162e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-3']</value>
      <webElementGuid>ed47a20d-e6a4-408d-b513-3e29625d13c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card-content/form/div/mat-form-field/div/div/div/input</value>
      <webElementGuid>513f152f-34c8-4bcd-aea8-f9ea63ea8378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'mat-input-3']</value>
      <webElementGuid>acdae801-af8b-4441-9146-66b48368f938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
