<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2037</name>
   <tag></tag>
   <elementGuidId>291bd2b3-7979-40be-9f90-5d706152d545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-option[@id='mat-option-27']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#mat-option-27 > span.mat-option-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e2152427-003f-41ee-874e-e4b99c4fa4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-option-text</value>
      <webElementGuid>a6c2f21d-274c-49d7-a6a9-ed2110c9225c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 2037 </value>
      <webElementGuid>32a6bfb6-fb33-4bb5-ae49-b92302aa9fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-option-27&quot;)/span[@class=&quot;mat-option-text&quot;]</value>
      <webElementGuid>82f0872c-6b7b-404d-9fdb-45fd93564f91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-option[@id='mat-option-27']/span</value>
      <webElementGuid>32af27dd-d865-46c8-b683-0a137e784934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'mat-option-27', '&quot;', ')/span[@class=', '&quot;', 'mat-option-text', '&quot;', ']')])[1]/following::span[16]</value>
      <webElementGuid>9728015d-35b2-446e-9d7f-51bd584ad0cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUE'])[1]/following::span[18]</value>
      <webElementGuid>e7b9c372-1625-4257-b3cf-6a97f7eb0d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2037']/parent::*</value>
      <webElementGuid>8867f6c9-e515-44e2-a90c-2c2e6ebdd43f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-option[16]/span</value>
      <webElementGuid>5c72a808-2848-4066-84d4-086c9f2aef4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' 2037 ' or . = ' 2037 ')]</value>
      <webElementGuid>e3276df3-5931-4ca2-8ff3-c6a339cbb4b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
