<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Logout_mat-focus-indicator headerLef_8384a0</name>
   <tag></tag>
   <elementGuidId>ae08b6bd-7962-4394-be32-5ea0e028eb69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-toolbar[@id='mainHeaderNav']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.headerLeft.mat-button.mat-button-base.cdk-focused.cdk-program-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e4f5c89c-5dd9-40c9-9b1e-0552f7ddc19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator headerLeft mat-button mat-button-base cdk-focused cdk-program-focused</value>
      <webElementGuid>44d1e5e4-ccfc-4f5c-a79e-060f65dab842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainHeaderNav&quot;)/button[@class=&quot;mat-focus-indicator headerLeft mat-button mat-button-base cdk-focused cdk-program-focused&quot;]</value>
      <webElementGuid>43b39409-61c6-4ece-a2c2-fba840f6bfb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-toolbar[@id='mainHeaderNav']/button</value>
      <webElementGuid>c089f11b-9820-4136-8a98-9054dd9b990c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::button[1]</value>
      <webElementGuid>f20aec63-f1b7-4359-9a26-e6a179af503f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Change Password'])[1]/following::button[2]</value>
      <webElementGuid>ef2aa915-2133-4581-80b8-6ea05b1c0ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[1]/preceding::button[4]</value>
      <webElementGuid>462fc051-3ff7-4809-9db2-ad8c75ba9fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Integrations'])[1]/preceding::button[5]</value>
      <webElementGuid>fdd4812e-cffa-4abe-b8c8-8d0ca3ed3522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-toolbar/button</value>
      <webElementGuid>82bfbed3-77db-48ca-8bb1-eec9e3634683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
