<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Close</name>
   <tag></tag>
   <elementGuidId>2f8e8708-be3b-45eb-85e6-7165a7e48d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-step-content-0-2']/form/div[2]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.mat-stroked-button.mat-button-base.mat-accent.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>99ae83e3-417c-4fa8-bed6-4e365f03d5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>accent</value>
      <webElementGuid>3f0f7b6e-d530-4003-a179-8077df16528f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-stroked-button mat-button-base mat-accent cdk-focused cdk-mouse-focused</value>
      <webElementGuid>cee4d537-fb66-417d-9a55-eb6fe38992d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>cec89a6a-a242-45e1-878e-78dadc0d0145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-2&quot;)/form[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;confirmationContentSpacing confirmationFooter ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator mat-stroked-button mat-button-base mat-accent cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>07b1079d-857a-402b-83a1-ee7ae51536ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8bdaca25-12bc-42a7-a6bc-0935a20368e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>accent</value>
      <webElementGuid>70dee983-96e9-49c3-a180-b2f51bb84ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator mat-stroked-button mat-button-base mat-accent cdk-focused cdk-mouse-focused</value>
      <webElementGuid>687e9048-10eb-492b-85bf-c026fd7b91e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>18c9f392-a8dc-417d-b44c-bddd5ec01424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-4-2&quot;)/form[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;confirmationContentSpacing confirmationFooter ng-star-inserted&quot;]/button[@class=&quot;mat-focus-indicator mat-stroked-button mat-button-base mat-accent cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>6ebd51f8-cc7b-497d-a6aa-0d83dbf0b5c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-2']/form/div[2]/button</value>
      <webElementGuid>e38780bf-f996-4546-b680-a66752ab91f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send copy:'])[1]/following::button[2]</value>
      <webElementGuid>7a86209e-7f64-40c2-8ee5-31f2cab3fe65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='blake.engrav@bngholdingsinc.com'])[1]/following::button[2]</value>
      <webElementGuid>ab61459d-c75d-481b-b628-7821514abb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div[2]/button</value>
      <webElementGuid>b729a648-4925-42cf-acdf-37898c838982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Close' or . = 'Close')]</value>
      <webElementGuid>0c3fd3fe-4bb9-447d-9f4b-2c433ffddea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-4-2']/form/div[2]/button</value>
      <webElementGuid>3882a521-94f7-44e0-8e6e-27e23368de26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
