<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_249,977.50</name>
   <tag></tag>
   <elementGuidId>9eef2a5e-00b9-4a39-9573-acae50c96fbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-invoice-information-modal/mat-toolbar/div/div[2]/div[2]/div[3]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>96c26993-393d-4e87-9360-26df8350e0d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>infoModalSubInfo</value>
      <webElementGuid>3e606ad9-1651-45e9-b69b-a78721d64c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $249,977.50 </value>
      <webElementGuid>6c106bb3-44c6-474a-ba7c-fd9263b7becb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-invoice-information-modal[@class=&quot;ng-star-inserted&quot;]/mat-toolbar[@class=&quot;mat-toolbar headerBar mat-primary mat-toolbar-single-row ng-star-inserted&quot;]/div[@class=&quot;infoHeader&quot;]/div[2]/div[@class=&quot;infoLeftSideTop&quot;]/div[@class=&quot;infoLeftContent&quot;]/div[@class=&quot;infoModalSubInfo&quot;]</value>
      <webElementGuid>511f3929-45b7-4855-ba51-d132100db490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e1da161b-b650-4df4-b604-8b34bd7d2885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>infoModalSubInfo</value>
      <webElementGuid>7c300982-b283-44e9-acef-173b6f3573c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $249,977.50 </value>
      <webElementGuid>a9f55bdb-5472-42bb-ac64-8aa46616d058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-invoice-information-modal[@class=&quot;ng-star-inserted&quot;]/mat-toolbar[@class=&quot;mat-toolbar headerBar mat-primary mat-toolbar-single-row ng-star-inserted&quot;]/div[@class=&quot;infoHeader&quot;]/div[2]/div[@class=&quot;infoLeftSideTop&quot;]/div[@class=&quot;infoLeftContent&quot;]/div[@class=&quot;infoModalSubInfo&quot;]</value>
      <webElementGuid>e56913aa-a4ff-435a-8d4b-6925c8713fd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-invoice-information-modal/mat-toolbar/div/div[2]/div[2]/div[3]/div[2]</value>
      <webElementGuid>a8e8fd03-5c12-42fa-8afa-02bdbb7d0c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance'])[2]/following::div[1]</value>
      <webElementGuid>bc36d886-c1b2-40f4-a50a-0c7589e150da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250,000.00'])[2]/following::div[3]</value>
      <webElementGuid>52014baa-19e9-40a1-954f-57e3e70e1e9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tran. Date'])[1]/preceding::div[1]</value>
      <webElementGuid>96c0407e-523a-41bc-b037-596426e70be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PO#'])[1]/preceding::div[4]</value>
      <webElementGuid>a6ee3b00-308d-489d-a451-9d71aaba2f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div[2]</value>
      <webElementGuid>5a653bbf-6274-4402-b756-2472a3738aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' $249,977.50 ' or . = ' $249,977.50 ')]</value>
      <webElementGuid>1eb6719d-ce7a-4e32-9c11-0b6720f7a427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
