<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Payment Successful</name>
   <tag></tag>
   <elementGuidId>dd10b95e-2787-4ed7-9dcf-8064809760da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-step-content-0-2']/form/div/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>205cbc7f-2015-478b-8d57-b0666bbde21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Payment successful</value>
      <webElementGuid>2b4a0d24-20e3-4a14-a883-efd8e21ef8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirmationPaymentSuccessfulHeader</value>
      <webElementGuid>c53e2c8c-6924-464d-999d-034936b900f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Payment Successful </value>
      <webElementGuid>40b3e37e-2fc5-4f05-bb9e-40d614b9c9a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-2&quot;)/form[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;confirmationList ng-star-inserted&quot;]/div[@class=&quot;successContainer&quot;]/div[@class=&quot;successSubContainer&quot;]/div[1]/div[@class=&quot;confirmationPaymentSuccessfulHeader&quot;]</value>
      <webElementGuid>cff7e341-cf29-47bf-9c46-09c6edcffd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f694a2a7-6b0f-49ea-a39f-7f9bd821c85d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Payment successful</value>
      <webElementGuid>dfeefdc3-606b-4a76-99e4-831dd1a8c052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>confirmationPaymentSuccessfulHeader</value>
      <webElementGuid>499431da-9b58-43f7-8dbc-b4c5dd0db062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Payment Successful </value>
      <webElementGuid>ebc9f045-9839-4613-9bbc-8cfb7e73ed81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-4-2&quot;)/form[@class=&quot;ng-untouched ng-pristine ng-valid ng-star-inserted&quot;]/div[@class=&quot;confirmationList ng-star-inserted&quot;]/div[@class=&quot;successContainer&quot;]/div[@class=&quot;successSubContainer&quot;]/div[1]/div[@class=&quot;confirmationPaymentSuccessfulHeader&quot;]</value>
      <webElementGuid>ec52e533-2f90-4491-a48f-be432b22d503</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-2']/form/div/div/div/div/div[2]</value>
      <webElementGuid>5bdba93a-8819-4283-b3f8-d65ac5763421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[1]/following::div[7]</value>
      <webElementGuid>b4b77bc0-a025-4b55-bd94-7ce3a452f8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::div[7]</value>
      <webElementGuid>0b15b3ad-02ca-47c0-95f7-48e56a43c1cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Details'])[1]/preceding::div[1]</value>
      <webElementGuid>951077fe-8541-4054-b204-68dd64884ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2.00'])[4]/preceding::div[2]</value>
      <webElementGuid>11ae4474-6256-47f7-9685-6c1ea029caf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Payment Successful']/parent::*</value>
      <webElementGuid>ebd98ec0-6603-4b6d-aaee-be4f937de563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/form/div/div/div/div/div[2]</value>
      <webElementGuid>7093b0d1-220f-476a-b418-527abab67f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' Payment Successful ' or . = ' Payment Successful ')]</value>
      <webElementGuid>5b63b0a1-8f6c-4f6d-8aaa-d671a4175680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-4-2']/form/div/div/div/div/div[2]</value>
      <webElementGuid>b255ea8e-c8ea-4cb8-82f9-b301509c5115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1.00'])[4]/preceding::div[2]</value>
      <webElementGuid>9fd1bd2b-ff57-40a1-bbb2-aca4be91a6b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
