<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Balance 250,000.00_mat-input-16</name>
   <tag></tag>
   <elementGuidId>96d17323-f704-4e6e-8c54-cd12beec6a5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mat-input-16</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-step-content-0-0']/form/div/div[2]/div/div[2]/div[2]/mat-form-field/div/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a671b8f-077e-4020-9817-f16b37ad2d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b9dd8bc1-266f-4cac-b610-cda0085da971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>amountToPay</value>
      <webElementGuid>0fa3b6e9-2f75-4b49-bc94-19d68ba99275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-input-element mat-form-field-autofill-control ng-tns-c73-106 ng-untouched ng-pristine ng-valid cdk-text-field-autofill-monitored</value>
      <webElementGuid>40523b8f-e870-40a5-8ffd-2f3b6461142b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mat-input-16</value>
      <webElementGuid>87fef877-feda-411f-b612-ff8a16a85bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>82a4981e-a6c1-4a93-b317-88471ce78ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47f11099-bfd4-437e-a054-23e9eabc491a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-input-16&quot;)</value>
      <webElementGuid>82199af4-27db-4fe8-8de1-830146d65e02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mat-input-16']</value>
      <webElementGuid>e12f02ad-f15e-42dc-9399-01cb7133f4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-0']/form/div/div[2]/div/div[2]/div[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>c9050ea2-da97-4df0-9d30-36babb1d1e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-form-field/div/div/div/input</value>
      <webElementGuid>caa24731-3541-4acb-b5ec-b606793cdaf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'mat-input-16']</value>
      <webElementGuid>be2d5610-03b4-4974-a6a4-3ab64daa226e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
