<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_Service_ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>5088ac16-1d6d-41dd-9c7a-4a3e00c08dc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>circle.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>0604a1da-3235-4293-8091-cc0a0284d77d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>a594b1f2-2745-430e-b795-45e751563954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>c4ef8c6f-b46d-4aa2-8a71-00001fde0a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>abcae2d4-87c8-4f54-92ec-c0fc90d1d64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>1e76cc5e-5c5c-432c-8af8-24db17026389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-tickets[@class=&quot;ng-star-inserted&quot;]/mat-spinner[@class=&quot;mat-spinner mat-progress-spinner mat-primary mat-progress-spinner-indeterminate-animation ng-star-inserted&quot;]/svg[1]/circle[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>9c878fa0-47b3-45ae-8e4a-8f453a1a960a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
