<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Payment History_chartjs-render-monitor</name>
   <tag></tag>
   <elementGuidId>a340ff40-b0e4-4b11-babd-fa8bf5a82b57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>canvas.chartjs-render-monitor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>343e0e64-0e98-4475-bf27-e6f99c90ac32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1643</value>
      <webElementGuid>f6ce8440-d2da-4916-9946-0b2d46622d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1232</value>
      <webElementGuid>d4d934ed-3de8-4ad4-a3bc-e57bd6faeebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chartjs-render-monitor</value>
      <webElementGuid>ea20e326-6c30-4c25-9990-e46b87dfd1d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dashboardGridTwo&quot;]/div[@class=&quot;cardPaymentHistory&quot;]/app-payment-history[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content ng-star-inserted&quot;]/div[1]/canvas[@class=&quot;chartjs-render-monitor&quot;]</value>
      <webElementGuid>1c5c01fc-55bf-487c-baca-4c886e409e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>cfa6ab97-2209-4ca6-b629-d0ca9f4a4ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1643</value>
      <webElementGuid>fc7d79a0-6fe0-42e4-a88b-a5f6cdc1219e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1232</value>
      <webElementGuid>5cc50cb9-3bc8-4ca3-bdda-0c3a18987cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chartjs-render-monitor</value>
      <webElementGuid>a4525e47-8770-40cd-be23-cf9086c2c5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dashboardGridTwo&quot;]/div[@class=&quot;cardPaymentHistory&quot;]/app-payment-history[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content ng-star-inserted&quot;]/div[1]/canvas[@class=&quot;chartjs-render-monitor&quot;]</value>
      <webElementGuid>be9c06b0-fdaf-45b8-9569-72cf81490ece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>74c1998e-954f-4c2a-877c-973ce04f5235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1643</value>
      <webElementGuid>47d13cec-84ba-4e2b-974c-58f45fd81bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1232</value>
      <webElementGuid>643b1dd1-ecf0-4cdb-bd20-375024f9ba85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chartjs-render-monitor</value>
      <webElementGuid>7d8427fd-e7f5-456f-bb96-2b99d840367a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dashboardGridTwo&quot;]/div[@class=&quot;cardPaymentHistory&quot;]/app-payment-history[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content ng-star-inserted&quot;]/div[1]/canvas[@class=&quot;chartjs-render-monitor&quot;]</value>
      <webElementGuid>7caa9863-e248-4bd6-8937-cb73ffd39e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>5fa542b5-b802-47d5-879a-8005cbce9ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1643</value>
      <webElementGuid>9346f9ff-d182-4d98-a1f7-f0ffab03614c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1232</value>
      <webElementGuid>516993c6-0292-49c0-af68-ee4e51265169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chartjs-render-monitor</value>
      <webElementGuid>bd4ca811-1659-4608-a9cc-0ad0c99432c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dashboardGridTwo&quot;]/div[@class=&quot;cardPaymentHistory&quot;]/app-payment-history[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content ng-star-inserted&quot;]/div[1]/canvas[@class=&quot;chartjs-render-monitor&quot;]</value>
      <webElementGuid>da60da4a-32b6-4750-af48-3907505b3484</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>d602d825-df5c-48bb-acfd-11a00ea82acb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
