<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_249,979.00</name>
   <tag></tag>
   <elementGuidId>81bae477-104d-4861-819f-cfea83dcf7fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.totalBalanceTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Balance'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>30c27fbe-75c2-4454-8467-46912d0158b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>totalBalanceTitle</value>
      <webElementGuid>8e20cb1d-bdbd-40ea-b0eb-576a8e0327a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $249,979.00 </value>
      <webElementGuid>514f6702-765f-4c8b-a03e-3543a590a073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dashboardGrid&quot;]/div[@class=&quot;cardTotalBalance&quot;]/app-total-balance[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content ng-star-inserted&quot;]/div[@class=&quot;totalBalanceTitle&quot;]</value>
      <webElementGuid>6d8b0d65-f25f-412c-a86c-1f12244f5425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7f5dabe-a3a7-41c1-8ca4-6ac23bc35135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>totalBalanceTitle</value>
      <webElementGuid>915971af-5d02-4520-ae45-b4d9a9d72818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $249,979.00 </value>
      <webElementGuid>3a13fffc-2528-4687-ac4b-93fbfd13c3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dashboardGrid&quot;]/div[@class=&quot;cardTotalBalance&quot;]/app-total-balance[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content ng-star-inserted&quot;]/div[@class=&quot;totalBalanceTitle&quot;]</value>
      <webElementGuid>e86ee17a-3f56-4c82-b8ca-d0ab4c6a5d80</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Balance'])[1]/following::div[1]</value>
      <webElementGuid>03df35ad-ebb1-4a88-8b37-ea1ba5e44a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service'])[1]/following::div[5]</value>
      <webElementGuid>70f15d2c-50ac-463b-bbf7-56156b518a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1 invoice)'])[1]/preceding::div[1]</value>
      <webElementGuid>d7acd076-49c4-42a2-b930-30db7d1fa074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Payment'])[1]/preceding::div[2]</value>
      <webElementGuid>03201d15-2d63-4761-b3ae-296435f44d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$249,979.00']/parent::*</value>
      <webElementGuid>bdaae514-c047-4ab5-8902-5eb2120a20d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card-content/div</value>
      <webElementGuid>479ce7fb-3376-4985-860e-b8486aa3f6a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' $249,979.00 ' or . = ' $249,979.00 ')]</value>
      <webElementGuid>c465900c-982e-4c87-81c0-ab1a99b8851f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
