<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_249,980.00</name>
   <tag></tag>
   <elementGuidId>9e0b6615-9c2f-484d-94ea-c481e8f2c106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.totalBalanceTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Balance'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c6591680-9895-4c2d-8daf-7e74d649ed5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>totalBalanceTitle</value>
      <webElementGuid>0db68be4-c52b-4045-a30d-2cbcd2a0aeca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $249,980.00 </value>
      <webElementGuid>e99c4d61-995e-4225-8c70-83dbaac740f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-dashboard[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;dashboardGrid&quot;]/div[@class=&quot;cardTotalBalance&quot;]/app-total-balance[1]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content ng-star-inserted&quot;]/div[@class=&quot;totalBalanceTitle&quot;]</value>
      <webElementGuid>ec57f8f2-f54c-4c96-b6a6-4a88792c231b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Balance'])[1]/following::div[1]</value>
      <webElementGuid>d117f1d5-a40b-4d47-9c94-4b9fcd50421e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service'])[1]/following::div[5]</value>
      <webElementGuid>1447b910-3791-41dd-b33a-2e98cd0a4f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(1 invoice)'])[1]/preceding::div[1]</value>
      <webElementGuid>8b5be59c-8e74-4eb8-9676-0c6caa403a21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make Payment'])[1]/preceding::div[2]</value>
      <webElementGuid>6d8b5c2a-9dd9-41e1-9cf0-5b84f11a1bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$249,980.00']/parent::*</value>
      <webElementGuid>dc48edb7-3ce1-4acf-b4cc-f4e4f29fd543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card-content/div</value>
      <webElementGuid>306a540c-c922-4a24-9d69-93d8271f08cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' $249,980.00 ' or . = ' $249,980.00 ')]</value>
      <webElementGuid>e87b2200-cd27-4df8-9303-a143a3f03944</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
