<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sync Integration Successful Close</name>
   <tag></tag>
   <elementGuidId>2dcbd526-810a-4410-838a-e78252d82ee9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cdk-overlay-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f9bb571b-e7bc-429d-b50f-256f9d77727b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cdk-overlay-1</value>
      <webElementGuid>9ba3526f-ba85-433b-9799-a079f914e7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdk-overlay-pane</value>
      <webElementGuid>3d49d0dc-1cc5-4f85-949e-5855e819c51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sync Integration Successful Close </value>
      <webElementGuid>bccd37db-9b7e-4ab8-964b-d3fdbe98f635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-1&quot;)</value>
      <webElementGuid>ea9c6663-1f66-4f82-a86b-c2b2b0b81da6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-1']</value>
      <webElementGuid>dd47a239-2530-4bcd-97d4-76ec909f07d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[1]/following::div[3]</value>
      <webElementGuid>9ce02e20-c213-408a-b8d2-c70c356499b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ConnectBooster Academy'])[1]/following::div[4]</value>
      <webElementGuid>2e7ec0d2-3d3b-44fc-96ad-0f909085d8d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>e246d4c3-c929-4eae-b010-7d2357dc783b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cdk-overlay-1' and (text() = 'Sync Integration Successful Close ' or . = 'Sync Integration Successful Close ')]</value>
      <webElementGuid>ae4ea476-4e61-4899-84a0-3c78c09a2686</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
