<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Test Connection Successful Close</name>
   <tag></tag>
   <elementGuidId>c93e7b72-5e5c-4e59-bc1b-29909e4ff8fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cdk-overlay-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dd7653fa-2a39-4319-8281-bf8aa3ffffb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cdk-overlay-1</value>
      <webElementGuid>acfdfd0a-5da1-494e-ba81-ff0d1b266472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdk-overlay-pane</value>
      <webElementGuid>ff075a86-5a11-48e8-94b5-6e034316fc6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Test Connection Successful Close </value>
      <webElementGuid>33937552-b42b-4114-b71c-0f3abb65265d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-1&quot;)</value>
      <webElementGuid>337a3c81-160c-47d7-88a1-a8bb26064bdd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-1']</value>
      <webElementGuid>746b0e49-5ae6-451e-895e-bd23e582da50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sort'])[1]/following::div[3]</value>
      <webElementGuid>7d15bd00-4d3e-4682-8e1d-03f84c2c970b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ConnectBooster Academy'])[1]/following::div[4]</value>
      <webElementGuid>0f3db055-a561-48b4-99e4-1636d68864ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>c9742496-686b-4102-9ca2-d834796b625f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cdk-overlay-1' and (text() = 'Test Connection Successful Close ' or . = 'Test Connection Successful Close ')]</value>
      <webElementGuid>ebd768c7-4237-41b0-9ff3-65fef23e16d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
