<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Highest Balances_chartjs-render-monitor</name>
   <tag></tag>
   <elementGuidId>cd13053c-4887-4641-b4c7-24df3f99db62</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>canvas.chartjs-render-monitor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//canvas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>e462b052-c554-43e5-8ec6-f7d8b90769ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chartjs-render-monitor</value>
      <webElementGuid>7d46ed6a-eba3-48f9-ba06-8ef4fa6c992d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>2347</value>
      <webElementGuid>0f8c5fc6-8b41-49ce-a6d3-b7c3be9bc60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1172</value>
      <webElementGuid>f8360e96-f77e-49af-b3e0-5b2cb1398ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-overview[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;grid&quot;]/app-highest-balance[@class=&quot;grid-item&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content ng-star-inserted&quot;]/div[1]/canvas[@class=&quot;chartjs-render-monitor&quot;]</value>
      <webElementGuid>961ad30c-d313-4fa8-8d8e-beb9c3552ce5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//canvas</value>
      <webElementGuid>1c6ee34b-5abb-4569-8e9c-b1ba21f28a13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
