<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_249,996.76</name>
   <tag></tag>
   <elementGuidId>e9ec5b04-4968-4885-a9ba-411f91fe0e88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='A/R by Company'])[1]/following::div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.arStats.totalOpenBalance</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5bbc48f4-9188-4c97-8ccb-633249901dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>arStats totalOpenBalance</value>
      <webElementGuid>edde1ca7-2235-46e1-9c4d-9e779b78bec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $249,996.76 </value>
      <webElementGuid>f87a1487-8e4f-4c96-8c7a-51c8e145dac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-overview[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;grid&quot;]/app-ar-widget[@class=&quot;grid-item&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator&quot;]/mat-card-content[@class=&quot;mat-card-content&quot;]/div[@class=&quot;arHeader ng-star-inserted&quot;]/div[1]/div[@class=&quot;arStats totalOpenBalance&quot;]</value>
      <webElementGuid>c3d34154-1eea-469d-921f-f3c955b70de8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A/R by Company'])[1]/following::div[3]</value>
      <webElementGuid>3b6ad4d8-e72e-4c47-b556-285e02307aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/preceding::div[1]</value>
      <webElementGuid>63caa51f-9801-4617-a8c2-fa81765d0393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$249,996.76']/parent::*</value>
      <webElementGuid>ac803f4e-9130-49ce-b121-f1f7cdc7ae30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-card-content/div/div/div</value>
      <webElementGuid>936509ed-85d2-4941-b9ec-d4dd569deddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' $249,996.76 ' or . = ' $249,996.76 ')]</value>
      <webElementGuid>c26022de-eadd-4c3f-9485-5758e6ca77e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
