<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_No Services for this company</name>
   <tag></tag>
   <elementGuidId>1b51a43b-d031-4100-9535-0857eb56dd43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-menu-panel-0']/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.noDropdown.ng-tns-c117-3.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49f7d35a-8e0e-46cd-8533-0913f916bc4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noDropdown ng-tns-c117-3 ng-star-inserted</value>
      <webElementGuid>591d8c71-d776-4ad1-b3da-3392351af4dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No Services for this company</value>
      <webElementGuid>0358a19c-dad7-43f5-bd16-cd3fcb60c3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-menu-panel-0&quot;)/div[@class=&quot;mat-menu-content ng-tns-c117-3&quot;]/div[@class=&quot;noDropdown ng-tns-c117-3 ng-star-inserted&quot;]</value>
      <webElementGuid>8c38d941-fc47-45b5-9539-f3d27d3a6e70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-menu-panel-0']/div/div</value>
      <webElementGuid>0acd7fca-d34f-4703-8c76-4685b9bc238b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::div[9]</value>
      <webElementGuid>8a208f00-9d1f-4738-8ac0-4ade5430e1e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::div[9]</value>
      <webElementGuid>4c5e999f-36ba-48a8-83b5-98490e031aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No Services for this company']/parent::*</value>
      <webElementGuid>d79e6208-abfb-4e44-b828-11a8990cf89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>a26948bb-56c2-4d49-a3b8-b5164b5dd618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'No Services for this company' or . = 'No Services for this company')]</value>
      <webElementGuid>18bd44fe-8fb1-4372-97d8-fa117e7b68e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
