<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>a712655a-102b-447e-84a8-f64e1ee1a7b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>96e0c953-b35f-4708-81d7-818952b6ba95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>7fe26f71-796e-49ee-a304-0933be1e27bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>679c5fd9-cd8b-477b-9b9e-2df1a2cb2f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>8bbc4fd5-2315-44fc-805c-37b4775d7d29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>9cec2f30-8ea7-4c05-965a-a3afff8fbdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/mat-spinner[@class=&quot;mat-spinner mat-progress-spinner mat-primary mat-progress-spinner-indeterminate-animation ng-star-inserted&quot;]/svg[1]/circle[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>2ce051d2-7e14-4d2f-9b99-fb9c9efb4ed7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
