<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pay Selected</name>
   <tag></tag>
   <elementGuidId>a9dde687-50d0-483a-a24b-b2172dea8a7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='open-invoices']/mat-card/app-open-customer-invoices/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.mat-focus-indicator.paySelectedColor.mat-raised-button.mat-button-base.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9dce031a-40c2-444b-9a28-3dba96abab5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator paySelectedColor mat-raised-button mat-button-base ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>36822cf1-c0a1-41d6-a7b4-54f4295d80ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay Selected</value>
      <webElementGuid>fd7f2695-d78c-421e-b36b-630ad9b35bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;open-invoices&quot;)/mat-card[@class=&quot;mat-card mat-focus-indicator content&quot;]/app-open-customer-invoices[1]/button[@class=&quot;mat-focus-indicator paySelectedColor mat-raised-button mat-button-base ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>d7b9d9f3-1b97-4229-829d-c80ae8b6891f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cac19069-c813-4a3c-b7c6-ee1f6ece4be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-focus-indicator paySelectedColor mat-raised-button mat-button-base ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>c6047721-2abe-4454-a1e0-d98797a216e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay Selected</value>
      <webElementGuid>e3b87264-1b95-4ab7-9374-60a64a216715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;open-invoices&quot;)/mat-card[@class=&quot;mat-card mat-focus-indicator content&quot;]/app-open-customer-invoices[1]/button[@class=&quot;mat-focus-indicator paySelectedColor mat-raised-button mat-button-base ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>5e72ff19-74f7-49a6-9a2d-c14fc6ef1714</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='open-invoices']/mat-card/app-open-customer-invoices/button</value>
      <webElementGuid>f6eda243-ee32-42aa-912c-7b42203f677a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Invoices'])[1]/following::button[1]</value>
      <webElementGuid>c53267eb-5ed3-490b-815d-faba201a0589</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# OF INVOICES'])[1]/following::button[2]</value>
      <webElementGuid>c0b45427-dfed-489c-88d2-5f9acb9e3585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Number'])[1]/preceding::button[1]</value>
      <webElementGuid>237d4f1e-abf2-4c8a-ad98-868f02f993e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-open-customer-invoices/button</value>
      <webElementGuid>0bae8118-dc89-4049-a7c5-f83d06f364e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Pay Selected' or . = 'Pay Selected')]</value>
      <webElementGuid>6a51b5ea-d276-4b11-a130-0feac78e1bd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
