<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Select Payment Method</name>
   <tag></tag>
   <elementGuidId>28719f54-d124-44b2-b8e0-87691e8093a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-step-content-0-0']/form/div/div/div/div[2]/mat-form-field/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mat-form-field-infix.ng-tns-c73-98</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e0861c0e-7c23-4461-ab27-923e99679371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c73-98</value>
      <webElementGuid>1785850b-f3e5-49ab-a4f0-152df29c4148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Payment Method</value>
      <webElementGuid>5d3722f2-0db6-4450-9f17-f288d0f3209a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-0&quot;)/form[@class=&quot;ng-untouched ng-pristine ng-star-inserted ng-invalid&quot;]/div[@class=&quot;detailContentSpacing detailTopRow&quot;]/div[@class=&quot;detailContentSpacing&quot;]/div[@class=&quot;detailTitles walletTitle&quot;]/div[@class=&quot;detailWallet&quot;]/mat-form-field[@class=&quot;mat-form-field paymentMethodSelector ng-tns-c73-98 mat-primary mat-form-field-type-mat-select mat-form-field-appearance-fill mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-star-inserted ng-invalid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c73-98&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c73-98&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c73-98&quot;]</value>
      <webElementGuid>598bac3c-2f3d-4faa-a3aa-7123db333387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35af0afb-c94b-4973-bb99-8e1291e26bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-form-field-infix ng-tns-c73-126</value>
      <webElementGuid>e3bdb13f-b038-4354-ba98-88d2244416c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Payment Method</value>
      <webElementGuid>f3f50611-8307-445c-9e76-07d58966e8f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-step-content-0-0&quot;)/form[@class=&quot;ng-untouched ng-pristine ng-star-inserted ng-invalid&quot;]/div[@class=&quot;detailContentSpacing detailTopRow&quot;]/div[@class=&quot;detailContentSpacing&quot;]/div[@class=&quot;detailTitles walletTitle&quot;]/div[@class=&quot;detailWallet&quot;]/mat-form-field[@class=&quot;mat-form-field paymentMethodSelector ng-tns-c73-126 mat-primary mat-form-field-type-mat-select mat-form-field-appearance-fill mat-form-field-can-float mat-form-field-has-label mat-form-field-hide-placeholder ng-untouched ng-pristine ng-star-inserted ng-invalid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c73-126&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c73-126&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c73-126&quot;]</value>
      <webElementGuid>73123767-b03d-4a95-9dc9-ac4a4cbf3da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-step-content-0-0']/form/div/div/div/div[2]/mat-form-field/div/div/div</value>
      <webElementGuid>f8be43b0-3a11-49a1-b9e4-7cb5611ff882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/following::div[10]</value>
      <webElementGuid>49871942-56dd-490c-90bd-2f837c8fc80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoices'])[1]/preceding::div[14]</value>
      <webElementGuid>19fcb163-8cf3-46a9-b185-51bfa6a852cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/mat-form-field/div/div/div</value>
      <webElementGuid>be990431-73f3-4314-aa1f-91506c4083ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Select Payment Method' or . = 'Select Payment Method')]</value>
      <webElementGuid>be79ce74-9237-46c5-a296-9c1d10bc8a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
