<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_249,995.26</name>
   <tag></tag>
   <elementGuidId>2b05208b-e0b4-477c-8a74-0ec505e6eede</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-dialog-container[@id='mat-dialog-0']/app-invoice-information-modal/mat-toolbar/div/div[2]/div[2]/div[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>48f863f6-d79a-48d3-a137-98305a7406cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>infoModalSubInfo</value>
      <webElementGuid>972f3175-2365-4cb7-b9f8-7d104172348f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> $249,995.26 </value>
      <webElementGuid>16aba8da-d081-4cde-9797-0fd82a61c87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-dialog-0&quot;)/app-invoice-information-modal[@class=&quot;ng-star-inserted&quot;]/mat-toolbar[@class=&quot;mat-toolbar headerBar mat-primary mat-toolbar-single-row ng-star-inserted&quot;]/div[@class=&quot;infoHeader&quot;]/div[2]/div[@class=&quot;infoLeftSideTop&quot;]/div[@class=&quot;infoLeftContent&quot;]/div[@class=&quot;infoModalSubInfo&quot;]</value>
      <webElementGuid>c4d8b127-609d-498a-a7dc-ffb606d3c1da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/app-invoice-information-modal/mat-toolbar/div/div[2]/div[2]/div[3]/div[2]</value>
      <webElementGuid>504e1718-ca45-4917-9d72-0b9ed55ee15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Balance'])[5]/following::div[1]</value>
      <webElementGuid>b65d832a-1f3e-4b3f-80b0-7ab87c0ae514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250,000.00'])[4]/following::div[3]</value>
      <webElementGuid>8bbcb96f-d37e-4ed9-9434-484ae29e85f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tran. Date'])[1]/preceding::div[1]</value>
      <webElementGuid>07a5428b-cf0b-4327-92b7-ccf8666157b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PO#'])[1]/preceding::div[4]</value>
      <webElementGuid>bbae6860-5fdf-4eb5-9491-5702d93bab35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[3]/div[2]</value>
      <webElementGuid>ccb7bc66-2160-4b31-b374-278e7f00f180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' $249,995.26 ' or . = ' $249,995.26 ')]</value>
      <webElementGuid>86e9e4fe-c6c5-4708-97be-7283fd82675d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
