<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Wallet_mat-select-placeholder mat-sele_4fa54e</name>
   <tag></tag>
   <elementGuidId>aef55052-7dd5-4376-bacd-876b58545aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mat-select-placeholder.mat-select-min-line.ng-tns-c125-56.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-7']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>45754950-fdb1-467d-b568-2447f83e730c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-placeholder mat-select-min-line ng-tns-c125-56 ng-star-inserted</value>
      <webElementGuid>7989c91a-dfce-417f-bffe-ad314055538a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-7&quot;)/span[@class=&quot;mat-select-placeholder mat-select-min-line ng-tns-c125-56 ng-star-inserted&quot;]</value>
      <webElementGuid>0d924bff-1257-4e6a-aa6a-7b676266eb47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-7']/span</value>
      <webElementGuid>26e0c066-ef59-4f68-b7b9-c4f31fa84891</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/following::span[4]</value>
      <webElementGuid>5c3ce777-8ee4-468a-b809-f731e99f6773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Payment Method'])[1]/preceding::span[1]</value>
      <webElementGuid>8444077d-ff15-46fc-9edf-d95f67d97990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoices'])[1]/preceding::span[3]</value>
      <webElementGuid>533901e1-7e14-49d6-b73b-e36cb5e21d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/mat-form-field/div/div/div/mat-select/div/div/span</value>
      <webElementGuid>de083cfa-a250-4fe5-b972-dd72390cbeb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
