<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Wallet_mat-select-placeholder mat-sele_4fa54e</name>
   <tag></tag>
   <elementGuidId>a4dd062e-8d26-4ba1-99c8-3b4ef7cc6ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mat-select-value-7']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.mat-select-placeholder.mat-select-min-line.ng-tns-c125-56.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3201b18a-e07b-4bc4-a487-5cfaca64380e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-select-placeholder mat-select-min-line ng-tns-c125-56 ng-star-inserted</value>
      <webElementGuid>57a65551-c77f-48ff-8819-c19ab440a13b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-select-value-7&quot;)/span[@class=&quot;mat-select-placeholder mat-select-min-line ng-tns-c125-56 ng-star-inserted&quot;]</value>
      <webElementGuid>917ac021-ce9f-4731-9c1e-a21ca96ac6e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mat-select-value-7']/span</value>
      <webElementGuid>90050f4a-ef2b-40c5-8aa2-65a443f70ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmation'])[1]/following::span[4]</value>
      <webElementGuid>1ff9c19c-26d2-4671-ae51-2a300fe84004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Payment Method'])[1]/preceding::span[1]</value>
      <webElementGuid>d4ff1401-fbf9-4197-ad08-7a3c14de8b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoices'])[1]/preceding::span[3]</value>
      <webElementGuid>9ce57404-38e7-40cb-90d4-d28d16697d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/mat-form-field/div/div/div/mat-select/div/div/span</value>
      <webElementGuid>4e20cc9e-3a71-42a3-86e4-cfeb7732872b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
