<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>circle_Service_ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>a7ac86aa-5eed-441c-b7af-ee56708d5465</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>circle.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>circle</value>
      <webElementGuid>83352655-58de-4c76-a9db-a0ed878301d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cx</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>38914aad-c02c-4685-b1e6-960c0264b87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cy</name>
      <type>Main</type>
      <value>50%</value>
      <webElementGuid>e1baacee-8bb3-4b83-b0d5-a687bfaec568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>r</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>714af718-70bb-4b54-b360-1d3b9f852b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-star-inserted</value>
      <webElementGuid>c467f6de-d500-4f55-a420-ee46ea945adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-end-client[1]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer ng-star-inserted&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-navigation[1]/app-projects[@class=&quot;ng-star-inserted&quot;]/mat-spinner[@class=&quot;mat-spinner mat-progress-spinner mat-primary mat-progress-spinner-indeterminate-animation ng-star-inserted&quot;]/svg[1]/circle[@class=&quot;ng-star-inserted&quot;]</value>
      <webElementGuid>1f69106e-3875-4e35-a6ee-9597715ff2e5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
