<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_company that REALLY loves invoices</name>
   <tag></tag>
   <elementGuidId>497e3d55-ee9c-4b59-941f-253ad9241b3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'company that REALLY loves invoices')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.clickableLinkGeneric</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98062d1f-12b3-4056-92ad-8558d8ee4ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickableLinkGeneric</value>
      <webElementGuid>971e092b-fd3d-49b5-a576-527a6497c595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> company that REALLY loves invoices </value>
      <webElementGuid>6b6d5581-04f3-4df1-b6d9-024c1576d5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-customers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 customersTable&quot;]/table[@class=&quot;mat-table cdk-table ng-star-inserted&quot;]/tbody[1]/mat-row[@class=&quot;mat-row cdk-row mat-ripple element-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-company mat-column-company ng-star-inserted&quot;]/a[@class=&quot;clickableLinkGeneric&quot;]</value>
      <webElementGuid>f620f3a8-3d94-4d6b-961e-261247599b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04476fa9-d42f-4794-921a-4509e66deb1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickableLinkGeneric</value>
      <webElementGuid>d3a18106-f89a-4a9f-a5ed-ec496776414b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> company that REALLY loves invoices </value>
      <webElementGuid>3abad354-3580-4969-b435-edc380962a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-customers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 customersTable&quot;]/table[@class=&quot;mat-table cdk-table ng-star-inserted&quot;]/tbody[1]/mat-row[@class=&quot;mat-row cdk-row mat-ripple element-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-company mat-column-company ng-star-inserted&quot;]/a[@class=&quot;clickableLinkGeneric&quot;]</value>
      <webElementGuid>bcd1fa45-43e1-4aba-b9ba-307f5b9db303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9105405-484c-4c0b-ad6b-c355450a0cda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickableLinkGeneric</value>
      <webElementGuid>733c6ae2-ad4a-413f-bbf5-886bc6ef389f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> company that REALLY loves invoices </value>
      <webElementGuid>3b860a49-8433-471f-8c66-4f77ba5ff63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-customers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 customersTable&quot;]/table[@class=&quot;mat-table cdk-table ng-star-inserted&quot;]/tbody[1]/mat-row[@class=&quot;mat-row cdk-row mat-ripple element-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-company mat-column-company ng-star-inserted&quot;]/a[@class=&quot;clickableLinkGeneric&quot;]</value>
      <webElementGuid>8083a480-c446-4fb7-87fd-369700436351</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'company that REALLY loves invoices')]</value>
      <webElementGuid>5d1f88b8-d7c3-4858-afed-75bced67f590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Total'])[1]/following::a[1]</value>
      <webElementGuid>aadabbd3-94ff-4316-bd73-245e01ac0335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Invoices'])[1]/following::a[1]</value>
      <webElementGuid>77865df4-9a59-4fc7-8727-0737ac8009f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,483.00'])[1]/preceding::a[1]</value>
      <webElementGuid>6e3b2e63-e235-47c2-95da-50e38a22f20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Funky Co-op'])[1]/preceding::a[1]</value>
      <webElementGuid>4eaa9492-67df-49a0-83d6-b842056260e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='company that REALLY loves invoices']/parent::*</value>
      <webElementGuid>d3a36cba-969d-4150-8e76-788730e08a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '')]</value>
      <webElementGuid>fc14b644-368e-44a6-80a1-74a170e0c8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>08dca737-c70e-4163-bcc5-9fb4ef96bf93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' company that REALLY loves invoices ' or . = ' company that REALLY loves invoices ')]</value>
      <webElementGuid>563cc12f-e8ec-44e8-8b73-47c0784a59aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,485.00'])[1]/preceding::a[1]</value>
      <webElementGuid>ff990db8-17ec-4a5d-8d73-ea444ada40d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$2,491.00'])[1]/preceding::a[1]</value>
      <webElementGuid>76fb2ad0-14de-4fad-8361-7d037cbaf0e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
