<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sun Microsystems - EBC</name>
   <tag></tag>
   <elementGuidId>d5713691-c817-483c-89ba-91d04df821a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Sun Microsystems - EBC')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.clickableLinkGeneric</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ce90d42-9384-4ec1-bc65-60a7d36c77cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickableLinkGeneric</value>
      <webElementGuid>0ab0d66a-fae7-4bf0-8927-ee87f93b2030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sun Microsystems - EBC </value>
      <webElementGuid>452f7f30-a1cc-4b6d-9567-8837430870ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-customers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 customersTable&quot;]/table[@class=&quot;mat-table cdk-table ng-star-inserted&quot;]/tbody[1]/mat-row[@class=&quot;mat-row cdk-row mat-ripple element-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-company mat-column-company ng-star-inserted&quot;]/a[@class=&quot;clickableLinkGeneric&quot;]</value>
      <webElementGuid>1de8ed54-fb87-4efc-9d36-461092091a18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a98a0266-1f86-47b1-9780-b546c6bf4f58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickableLinkGeneric</value>
      <webElementGuid>57516506-07a2-46e0-83cd-8de16a4025c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sun Microsystems - EBC </value>
      <webElementGuid>6f2a6bbd-d720-420c-a427-6f74a6fc226d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-customers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 customersTable&quot;]/table[@class=&quot;mat-table cdk-table ng-star-inserted&quot;]/tbody[1]/mat-row[@class=&quot;mat-row cdk-row mat-ripple element-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-company mat-column-company ng-star-inserted&quot;]/a[@class=&quot;clickableLinkGeneric&quot;]</value>
      <webElementGuid>4b22dd80-842f-4e55-9a7c-90f6853c3d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>61bed26c-2394-46fd-bd8d-42b2b0f13272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickableLinkGeneric</value>
      <webElementGuid>7acb4a21-f042-42b7-b48c-2bef2f0dbbc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sun Microsystems - EBC </value>
      <webElementGuid>9817f488-05e3-47b6-935a-0182dedae920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-customers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 customersTable&quot;]/table[@class=&quot;mat-table cdk-table ng-star-inserted&quot;]/tbody[1]/mat-row[@class=&quot;mat-row cdk-row mat-ripple element-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-company mat-column-company ng-star-inserted&quot;]/a[@class=&quot;clickableLinkGeneric&quot;]</value>
      <webElementGuid>989ef1b0-424d-4199-8b4d-e3b5b010ed17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d972b32f-74a3-45ce-aac6-2b8409adf524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickableLinkGeneric</value>
      <webElementGuid>a69ee8b4-b23a-4d14-8c68-74adb1169172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sun Microsystems - EBC </value>
      <webElementGuid>33348c84-1dba-41b3-999a-aa409907f1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-customers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 customersTable&quot;]/table[@class=&quot;mat-table cdk-table ng-star-inserted&quot;]/tbody[1]/mat-row[@class=&quot;mat-row cdk-row mat-ripple element-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-company mat-column-company ng-star-inserted&quot;]/a[@class=&quot;clickableLinkGeneric&quot;]</value>
      <webElementGuid>45c46b8b-c102-475a-b97c-954f2bc4c2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f44f7d1d-915a-4a2c-9eda-b1d61bb35b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickableLinkGeneric</value>
      <webElementGuid>26b9c447-467f-461b-97d1-7f817d464bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sun Microsystems - EBC </value>
      <webElementGuid>6bcd8d11-452e-4698-b4a4-864d4e7ffb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-customers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 customersTable&quot;]/table[@class=&quot;mat-table cdk-table ng-star-inserted&quot;]/tbody[1]/mat-row[@class=&quot;mat-row cdk-row mat-ripple element-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-company mat-column-company ng-star-inserted&quot;]/a[@class=&quot;clickableLinkGeneric&quot;]</value>
      <webElementGuid>62adf284-8b20-4d6a-a671-d4074f409c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2706ff27-9e80-4e8c-9fbd-1db491677b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickableLinkGeneric</value>
      <webElementGuid>6fd533f4-858a-4d39-abde-a4386e253cf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sun Microsystems - EBC </value>
      <webElementGuid>d50c6423-6758-460c-811e-efdfb39523a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mat-typography&quot;]/app-root[1]/app-portal[@class=&quot;ng-star-inserted&quot;]/mat-sidenav-container[@class=&quot;mat-drawer-container mat-sidenav-container contentContainer mat-drawer-transition&quot;]/mat-sidenav-content[@class=&quot;mat-drawer-content mat-sidenav-content&quot;]/app-customers[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;mat-elevation-z8 customersTable&quot;]/table[@class=&quot;mat-table cdk-table ng-star-inserted&quot;]/tbody[1]/mat-row[@class=&quot;mat-row cdk-row mat-ripple element-row ng-star-inserted&quot;]/mat-cell[@class=&quot;mat-cell cdk-cell cdk-column-company mat-column-company ng-star-inserted&quot;]/a[@class=&quot;clickableLinkGeneric&quot;]</value>
      <webElementGuid>13b58405-1d3d-4050-a454-bfffb95bf3d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sun Microsystems - EBC')]</value>
      <webElementGuid>0a60701f-9b63-40a3-aece-9528918e4b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Invoice Total'])[1]/following::a[1]</value>
      <webElementGuid>aa7032c2-0bef-44f2-97be-1035b1a7b97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Open Invoices'])[1]/following::a[1]</value>
      <webElementGuid>080d75cb-22be-4dcb-bbb3-0be1f8bcfd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$249,993.54'])[1]/preceding::a[1]</value>
      <webElementGuid>f99e406b-07ca-4b54-8614-11d34934203a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Policy'])[1]/preceding::a[1]</value>
      <webElementGuid>b3e7b3ba-56b5-4b88-9567-25dc8270e1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sun Microsystems - EBC']/parent::*</value>
      <webElementGuid>481889bd-01cc-474f-8b8e-23c9484d8734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '')]</value>
      <webElementGuid>0c307e7c-c843-4233-81c2-445337a5df8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>65bcfefb-9954-41fa-b03b-a18e3dcc4a09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = ' Sun Microsystems - EBC ' or . = ' Sun Microsystems - EBC ')]</value>
      <webElementGuid>f5a01c69-1f7a-4651-84e5-0a30480dfa1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$249,996.76'])[1]/preceding::a[1]</value>
      <webElementGuid>f3ae2c86-7aac-4664-ad03-5dae85b1533d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$249,997.76'])[1]/preceding::a[1]</value>
      <webElementGuid>8d26144a-a328-4266-b75f-5a545c375b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$249,988.00'])[1]/preceding::a[1]</value>
      <webElementGuid>f095a899-7f2a-463f-8193-7cc40f667b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$249,999.00'])[1]/preceding::a[1]</value>
      <webElementGuid>d8cf327b-f1c9-4d83-92c7-dd45023aae58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$250,000.00'])[1]/preceding::a[1]</value>
      <webElementGuid>cb59c2b1-c8fa-4dec-94d3-352aef157951</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
